#!/usr/bin/env python
# coding: utf-8
# *****************************************************************************
#  * @file    stdatalog_plot.py
#  * @author  SRA
# ******************************************************************************
# * @attention
# *
# * Copyright (c) 2022 STMicroelectronics.
# * All rights reserved.
# *
# * This software is licensed under terms that can be found in the LICENSE file
# * in the root directory of this software component.
# * If no LICENSE file comes with this software, it is provided AS-IS.
# *
# *
# ******************************************************************************
"""
This script, `stdatalog_plot.py`, is designed to plot data from acquisition folders
generated by STMicroelectronics' HSDatalog tool. It supports various options for customizing
the plots, including selecting specific sensors, setting time ranges, plotting raw data,
including annotations, and more.
It uses Plotly within Dash applications to create interactive visualizations and Click
for command-line interface options.
The script can be run from the command line with various options to tailor the data
visualization to the user's needs.

Key Features:
- Plot data for specific sensors or all active components.
- Set start and end times for the data plot.
- Option to plot raw data.
- Include annotations in the plot.
- Filter data by tag labels.
- Create subplots for multi-dimensional sensors.
- Display frequency plots for inertial sensors and microphones.
- Upload and use a custom Device Template Model (DTDL).
- Enable debug mode to check for corrupted data and timestamps.
"""

import sys
import os
import click

# Add the STDatalog SDK root directory to the sys.path to access the SDK packages
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

import logging
logging.getLogger('werkzeug').setLevel(logging.ERROR)
logging.getLogger('dash').setLevel(logging.ERROR)

from stdatalog_core.HSD_utils.dtm import HSDatalogDTM
from stdatalog_core.HSD_utils.exceptions import MissingDeviceModelError, \
    MissingISPUOutputDescriptorException
import stdatalog_core.HSD_utils.logger as logger
from stdatalog_core.HSD.HSDatalog import HSDatalog

log = logger.setup_applevel_logger(is_debug = False, file_name= "app_debug.log")
script_version = "1.0.0"

def show_help(ctx, param, value):
    """Print CLI help and usage examples, then exit.

    Parameters
    ----------
    ctx : click.Context
        The Click context.
    param : click.Option
        The option that triggered the callback.
    value : bool
        Whether the help flag was provided.
    """
    _ = param  # Unused parameter
    if value and not ctx.resilient_parsing:
        # Display the help information for the command
        click.secho(ctx.get_help(), color=ctx.color)
        # Display examples of script execution
        click.secho("\n-> Script execution examples:")
        # Example: Plot data for a specific acquisition folder
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path", fg='cyan')
        # Example: Plot data for a specific sensor
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -s Sensor_Name", fg='cyan')
        # Example: Plot data with a specific start and end time
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -st 3 -et 6", fg='cyan')
        # Example: Plot raw data (not multiplied by sensitivity)
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -r", fg='cyan')
        # Example: Plot data including annotations (if any in the acquisition)
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -l", fg='cyan')
        # Example: Plot data with labels. User can select which labels to plot (available labels are filtered by the provided list)
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -tl tag1 -tl tag2", fg='cyan')
        # Example: Plot data in subplots (one subplot for each sensor axis)
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -p", fg='cyan')
        # Example: Plot frequency plots (spectrogram) for inertial sensors and microphones
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -fp", fg='cyan')
        # Example: Upload a custom device model
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -cdm 1 2 custom_model.json", fg='cyan')
        # Example: Enable debug mode (Check Timestamp consistency)
        click.secho("   python stdatalog_plot.py Acquisition_Folder_Path -d", fg='cyan')
        ctx.exit()

@click.command()
@click.argument('acq_folder', type=click.Path(exists=True))
@click.option('-s', '--sensor_name', help="Component name (Sensor or Algorithm) - use \"all\" to extract all active Component data, otherwise select a specific Component by name", default='')
@click.option('-st','--start_time', help="Start Time - Data plot will start from this time (seconds)", type=int, default=0)
@click.option('-et','--end_time', help="End Time - Data plot will end up in this time (seconds)", type=int, default=-1)
@click.option('-r', '--raw_data', is_flag=True, help="Uses Raw data (not multiplied by sensitivity)", default=False)
@click.option('-l', '--labeled', is_flag=True, help="Plot data including information about annotations taken during acquisition (if any)", default=False)
@click.option('-tl', '--tag_labels', multiple=True, help='A list of tag labels strings to filter and include only the corresponding entries in the converted output')
@click.option('-p', '--subplots', is_flag=True, help="Multiple subplot for multi-dimensional sensors", default=False)
@click.option('-fp', '--fft_plots', is_flag=True, help="Display frequency plots for inertial sensors and microphones", default=False)
@click.option('-cdm','--custom_device_model', help="Upload a custom Device Template Model (DTDL)", type=(int, int, str))
@click.version_option(script_version, '-v', '--version', prog_name="stdatalog_plot", is_flag=True, help="stdatalog_plot tool version number")
@click.option('-d', '--debug', is_flag=True, help="[DEBUG] Check for corrupted data and timestamps", default=False)
@click.option("-h"," --help", is_flag=True, is_eager=True, expose_value=False, callback=show_help, help="Show this message and exit.",)

# Define the main function that will be executed when the script is run
def hsd_plot(
    acq_folder,
    sensor_name,
    start_time,
    end_time,
    raw_data,
    labeled,
    tag_labels,
    subplots,
    fft_plots,
    custom_device_model,
    debug,
):
    """Plot acquisition data in Dash/Plotly with optional FFT and labels.

    Parameters
    ----------
    acq_folder : str
        Path to the acquisition folder.
    sensor_name : str
        Component name to plot, or 'all' for all active components, or empty
        to prompt selection.
    start_time : int
        Start time in seconds for plotting.
    end_time : int
        End time in seconds for plotting (-1 to the end).
    raw_data : bool
        Use raw data values (no sensitivity applied).
    labeled : bool
        If True, plotting includes acquisition labels where available.
    tag_labels : tuple[str]
        Optional tag labels to filter plotted data; enables labeled mode.
    subplots : bool
        If True, create multiple subplots for multi-dimensional sensors.
    fft_plots : bool
        If True, include frequency plots for inertial/microphone data.
    custom_device_model : tuple[int, int, str] | None
        Optional custom DTDL (board_id, fw_id, json_path).
    debug : bool
        Enable timestamp recovery checks and debug logging.
    """

    # If a custom device model is provided, upload it using the HSDatalogDTM module
    if custom_device_model is not None:
        HSDatalogDTM.upload_custom_dtm(custom_device_model)

    # Create an instance of the HSDatalog factory
    hsd_factory = HSDatalog()
    try:
        # Create an HSDatalog object for the given acquisition folder
        hsd = hsd_factory.create_hsd(acq_folder)
    except MissingDeviceModelError as error:
        # Handle the case where the device model is missing and log the error
        log.error("Device Template Model identifyed by [%s] not supported", error)
        log.info("Check your input acquisition folder, then try to upload a" \
                    "custom Device Template Model using -cdm flag")
        return

    # Process tag labels if provided as selection filter
    which_tags = []
    if len(tag_labels) > 0:
        which_tags = list(tag_labels)
        labeled = True

    # Enable timestamp recovery if debug mode is on
    hsd.enable_timestamp_recovery(debug)

    # Main loop to plot data
    plot_flag = True
    while plot_flag:
        # If no sensor name is provided, ask the user to select a component
        if sensor_name == '':
            # If a component is selected, plot its data
            component = HSDatalog.ask_for_component(hsd, only_active=True)
            if component is not None:
                label = ask_for_label(hsd, labeled)
                plot(hsd, component, start_time, end_time, label, which_tags, subplots,
                    raw_data, acq_folder, fft_plots)
            else:
                break
        # If 'all' is specified for sensor name, plot all active components
        elif sensor_name == 'all':
            component_list = HSDatalog.get_all_components(hsd, only_active=True)
            label = ask_for_label(hsd, labeled)
            for component in component_list:
                plot(hsd, component, start_time, end_time, label, which_tags, subplots,
                    raw_data, acq_folder, fft_plots)
            if not labeled:
                plot_flag = False
        # If a specific sensor name is provided, plot only that component
        else:
            component = HSDatalog.get_component(hsd, sensor_name)
            if component is not None:
                label = ask_for_label(hsd, labeled)
                plot(hsd, component, start_time, end_time, label, which_tags, subplots,
                    raw_data, acq_folder, fft_plots)
            else:
                # Log an error if the specified component is not found
                log.error('No "%s" Component to plot found' \
                ' in your Device Configuration file', sensor_name)
                quit()
            if not labeled:
                plot_flag = False
    log.info("--> Plotting completed!")
    # Wait for user input before closing the console
    input("Press Enter to exit...")  # Keep the console open until the user presses Enter
    hsd.close_plot_threads()  # Close any open plot threads

# Define a helper function to ask the user for a label if the data is labeled
def ask_for_label(hsd, labeled):
    """Ask the user to pick a label, if labeling is enabled.

    Parameters
    ----------
    hsd : Any
        HSDatalog instance for the acquisition.
    labeled : bool
        Whether labeling is enabled.

    Returns
    -------
    str | None
        Selected label, or None when not labeled or user cancels.
    """
    label = None
    if labeled:
        label_list = hsd.get_acquisition_label_classes()
        label = hsd.prompt_label_select_CLI(label_list)
        if label is not None:
            log.info(label)
        else:
            quit()
    return label

# Define a helper function to plot data for a specific component
def plot(
    hsd,
    component,
    start_time,
    end_time,
    label,
    which_tags,
    subplots,
    raw_data,
    acq_folder,
    fft_plots,
):
    """Render plots for a specific component using HSDatalog.plot.

    Parameters
    ----------
    hsd : Any
        HSDatalog instance for the acquisition.
    component : dict
        Component descriptor from HSDatalog.
    start_time : int
        Start time in seconds for plotting.
    end_time : int
        End time in seconds for plotting.
    label : str | None
        Label class to visualize and filter by.
    which_tags : list[str]
        Optional tag labels to filter plotted data.
    subplots : bool
        Create one subplot per data column (except Time).
    raw_data : bool
        Use raw data values (no sensitivity applied).
    acq_folder : str
        Acquisition folder path used for error messages.
    fft_plots : bool
        Include frequency plots for inertial sensors and microphones.
    """
    try:
        df = HSDatalog.plot(hsd, component, start_time, end_time, label, which_tags,
                            subplots, raw_data, fft_plots)
        return df
    except MissingISPUOutputDescriptorException as ispu_err:
        # Handle missing ISPU output descriptor exception
        log.error(ispu_err)
        log.warning(
                "Please copy the right ISPU configuration file (JSON) in your "
                f'"{acq_folder}" '
                'acquisition folder.'
            )
    except Exception as err:
        log.exception(err)

if __name__ == '__main__':
    # Execute the main function
    hsd_plot()
