#!/usr/bin/env python
# coding: utf-8
# *****************************************************************************
#  * @file    stdatalog_dataframes.py
#  * @author  SRA
# ******************************************************************************
# * @attention
# *
# * Copyright (c) 2022 STMicroelectronics.
# * All rights reserved.
# *
# * This software is licensed under terms that can be found in the LICENSE file
# * in the root directory of this software component.
# * If no LICENSE file comes with this software, it is provided AS-IS.
# *
# *
# ******************************************************************************
"""
This script, `stdatalog_dataframes.py`, is designed to extract pandas dataframes from acquisition
folders generated by STMicroelectronics' HSDatalog tool. It supports various options for customizing
the data extraction, including selecting specific sensors, setting time ranges, extracting raw data,
including annotations, and more.
It uses Click for command-line interface options and logs information and errors during execution.
The script can be run from the command line with various options to tailor the data extraction
to the user's needs.

Key Features:
- Extract dataframes for specific sensors or all active components.
- Set start and end times for the data extraction.
- Option to extract raw data.
- Include annotations in the extracted dataframes.
- Filter data by tag labels.
- Specify the size of each data chunk to be processed.
- Upload and use a custom Device Template Model (DTDL).
- Enable debug mode to check for corrupted data and timestamps.
"""

import sys
import os
import click

# Add the STDatalog SDK root directory to the sys.path to access the SDK packages
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from stdatalog_core.HSD_utils.dtm import HSDatalogDTM
from stdatalog_core.HSD_utils.exceptions import MissingDeviceModelError, MissingTagsException, \
    MissingISPUOutputDescriptorException
import stdatalog_core.HSD_utils.logger as logger
from stdatalog_core.HSD.HSDatalog import HSDatalog

# Set up the application logger to record debug information and errors
log = logger.setup_applevel_logger(is_debug = False, file_name= "app_debug.log")

# Define the script version for reference
script_version = "1.0.0"

# Define a callback function to show help information
def show_help(ctx, param, value):
    """Callback to display help and usage examples.

    Parameters:
    - ctx: click.Context for the current command invocation.
    - param: click.Option parameter (`--help`).
    - value: bool flag indicating whether help was requested.

    Behavior:
    - Prints command help and curated usage examples.
    - Exits the context after printing help when invoked.
    """
    _ = param  # Unused parameter
    if value and not ctx.resilient_parsing:
        # Display the help information for the command
        click.secho(ctx.get_help(), color=ctx.color)
        # Display examples of script execution
        click.secho("\n-> Script execution examples:")
        # This command will extract dataframes for all active sensors from the specified acquisition folder.
        click.secho("   python stdatalog_dataframes.py Acquisition_Folder_Path -s all", fg='cyan')
        # This command will extract dataframes for all active sensors and include annotations in the output.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -s all -l", fg='cyan')
        # This command will extract raw dataframes (not multiplied by sensitivity) for a specific sensor named SENSOR_NAME.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -s SENSOR_NAME -r", fg='cyan')
        # This command will extract dataframes for the sensor SENSOR_NAME, starting from 3 seconds and ending at 6 seconds.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -st 3 -et 6 -s SENSOR_NAME", fg='cyan')
        # This command will extract dataframes for all active sensors, but only include entries that have the tag labels SW_TAG_0 or SW_TAG_2.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -tl SW_TAG_0 -tl SW_TAG_2 -s all", fg='cyan')
        # This command will upload a custom Device Template Model (DTDL) "custom_model.json" with board_id=0xff, fw_id=0xff and extract dataframes for the sensor SENSOR_NAME.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -cdm 255 255 custom_model.json -s SENSOR_NAME", fg='cyan')
        # This command will specify the size of each data chunk to be 1000 samples for the sensor SENSOR_NAME.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -cs 1000 -s SENSOR_NAME", fg='cyan')
        # This command will extract dataframes for the sensor SENSOR_NAME and check for corrupted data and timestamps.
        click.secho("   python stdatalog_dataframes.py path_to_acquisition_folder -d -s SENSOR_NAME", fg='cyan')
        # Exit the context after showing help
        ctx.exit()

# Define the click command with options for the data export script
@click.command()
@click.argument('acq_folder', type=click.Path(exists=True))
@click.option('-s', '--sensor_name', help="Sensor Name - use \"all\" to obtain all active sensors dataframes, otherwise select a specific sensor by name", default='')
@click.option('-st','--start_time', help="Start Time - Data conversion will start from this time (seconds)", type=int, default=0)
@click.option('-et','--end_time', help="End Time - Data conversion will end up in this time (seconds)", type=int, default=-1)
@click.option('-r', '--raw_data', is_flag=True, help="Uses Raw data (not multiplied by sensitivity)", default=False)
@click.option('-l', '--labeled', is_flag=True, help="Includes annotations taken during acquisition (if any) in the extracted dataframe", default=False)
@click.option('-tl', '--tag_labels', multiple=True, help='A list of tag labels strings to filter and include only the corresponding entries in the output dataframe')
@click.option('-cdm','--custom_device_model', help="Upload a custom Device Template Model (DTDL)", type=(int, int, str))
@click.option('-cs', '--chunk_size', help="Specify the size (number of samples) of each data chunk to be processed", default=HSDatalog.DEFAULT_SAMPLES_CHUNK_SIZE)
@click.version_option(script_version, '-v', '--version', prog_name="stdatalog_dataframes", is_flag=True, help="stdatalog_dataframes tool version number")
@click.option('-d', '--debug', is_flag=True, help="[DEBUG] Check for corrupted data and timestamps", default=False)
@click.option('-dlg', '--disable_lazy_generator', is_flag=True, help="Disable lazy generator for dataframes extraction", default=False)
@click.option("-h", "--help", is_flag=True, is_eager=True, expose_value=False, callback=show_help, help="Show this message and exit.",)

# Define the main function that will be executed when the script is run
def hsd_dataframe(
    acq_folder,
    sensor_name,
    start_time,
    end_time,
    raw_data,
    labeled,
    tag_labels,
    custom_device_model,
    chunk_size,
    debug,
    disable_lazy_generator,
):
    """Extract pandas dataframes from an acquisition folder.

    Parameters:
    - acq_folder: str path to the acquisition folder.
    - sensor_name: str sensor/component name; use `all` for all active.
    - start_time: int start time (seconds) for extraction interval.
    - end_time: int end time (seconds) for extraction interval; `-1` means full.
    - raw_data: bool return raw values (not multiplied by sensitivity).
    - labeled: bool include annotations if present.
    - tag_labels: tuple[str] optional tag labels filter.
    - custom_device_model: tuple[int, int, str] board_id, fw_id, json path.
    - chunk_size: int samples per processed chunk.
    - debug: bool enable timestamp recovery and extra checks.
    - disable_lazy_generator: bool disable generator-based extraction.

    Returns:
    - None
    """

    # Check if the lazy generator is disabled or not
    use_generator = not disable_lazy_generator

    # If a custom device model is provided, upload it
    if custom_device_model is not None:
        HSDatalogDTM.upload_custom_dtm(custom_device_model)

    # Create an instance of the HSDatalog factory
    hsd_factory = HSDatalog()
    try:
        # Create an HSDatalog object for the given acquisition folder
        hsd = hsd_factory.create_hsd(acq_folder)
    except MissingDeviceModelError as error:
        # Handle the case where the device model is missing
        log.error("Device Template Model identifyed by [%s] not supported", error)
        log.info("Check your input acquisition folder, then try to upload a custom " \
            "Device Template Model using -cdm flag")
        return

    # Process tag labels if provided as selection filter
    which_tags = []
    if len(tag_labels) > 0:
        which_tags = list(tag_labels)
        labeled = True

    # Enable timestamp recovery if debug mode is active
    hsd.enable_timestamp_recovery(debug)

    # Process dataframes based on the sensor name provided
    df_flag = True
    while df_flag:
        # If no sensor name is provided, ask the user to select a component
        if sensor_name == '':
            component = HSDatalog.ask_for_component(hsd, only_active=True)
            # If a component is selected, extract a dataframe from its data
            if component is not None:
                extract_component_dataframe(hsd, component, start_time, end_time, labeled,
                                            which_tags, raw_data, chunk_size, acq_folder,
                                            use_generator)
            else:
                break
        # If 'all' is specified for sensor name, process all active components
        elif sensor_name == 'all':
            component_list = HSDatalog.get_all_components(hsd, only_active=True)
            for component in component_list:
                extract_component_dataframe(hsd, component, start_time, end_time, labeled,
                                            which_tags, raw_data, chunk_size, acq_folder,
                                            use_generator)
            df_flag = False
        # If a specific sensor name is provided, process only that component
        else:
            component = HSDatalog.get_component(hsd, sensor_name)
            if component is not None:
                extract_component_dataframe(hsd, component, start_time, end_time, labeled,
                                            which_tags, raw_data, chunk_size, acq_folder,
                                            use_generator)
            else:
                # Log an error if the specified component is not found
                log.error('No "%s" Component found in your Device Configuration file', sensor_name)
            df_flag = False

def extract_component_dataframe(
    hsd,
    component,
    start_time,
    end_time,
    labeled,
    which_tags,
    raw_data,
    chunk_size,
    acq_folder,
    use_generator=True,
):
    """Extract and log dataframes for a single component.

    Parameters:
    - hsd: HSDatalog instance.
    - component: object representing the component to extract.
    - start_time: int start time (seconds).
    - end_time: int end time (seconds).
    - labeled: bool include annotations if present.
    - which_tags: list[str] tag labels filter.
    - raw_data: bool return raw values.
    - chunk_size: int samples per chunk.
    - acq_folder: str acquisition folder path.
    - use_generator: bool use generator-based extraction.

    Returns:
    - None
    """
    if use_generator:
        df_generator = extract_dataframe(hsd, component, start_time, end_time, labeled,
                                        which_tags, raw_data, chunk_size, acq_folder, True)
        if df_generator is not None:
            for df in df_generator:
                log.info("\nDataFrame: %s", df)
    else:
        df_list = extract_dataframe(hsd, component, start_time, end_time, labeled,
                                    which_tags, raw_data, chunk_size, acq_folder, False)
        if df_list is not None:
            for df in df_list:
                if not df.empty:
                    log.info("\nDataFrame: %s", df)

def extract_dataframe(
    hsd,
    component,
    start_time,
    end_time,
    labeled,
    which_tags,
    raw_data,
    chunk_size,
    acq_folder,
    use_generator=True,
):
    """Return dataframes for a component, optionally via generator.

    Parameters:
    - hsd: HSDatalog instance.
    - component: object representing the component to extract.
    - start_time: int start time (seconds).
    - end_time: int end time (seconds).
    - labeled: bool include annotations if present.
    - which_tags: list[str] tag labels filter.
    - raw_data: bool return raw values.
    - chunk_size: int samples per chunk.
    - acq_folder: str acquisition folder path (for error messaging).
    - use_generator: bool when True, yields dataframes lazily.

    Returns:
    - Generator[pandas.DataFrame] | list[pandas.DataFrame] | None
    """
    try:
        # Extract dataframes based on the provided parameters
        if use_generator:
            return HSDatalog.get_dataframe_gen(hsd, component, start_time, end_time, labeled,
                                            raw_data, which_tags, chunk_size)
        else:
            return HSDatalog.get_dataframe(hsd, component, start_time, end_time, labeled,
                                        raw_data, which_tags, chunk_size)

    except MissingTagsException as tags_err:
        # Handle missing tags exception
        log.error(tags_err)
        log.warning("Check \"tags\" field in your acquisition_info.json file" \
                    " (AcquisitionInfo.json for HSDv1 acquisitions)")
        quit()
    except MissingISPUOutputDescriptorException as ispu_err:
        # Handle missing ISPU output descriptor exception
        log.error(ispu_err)
        log.warning(
                "Please copy the right ISPU configuration file (JSON) in your "
                f'"{acq_folder}" '
                'acquisition folder.'
            )
    except Exception as err:
        log.exception(err)

if __name__ == '__main__':
    # Execute the main function
    hsd_dataframe()
